/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import customization.MaturityLevel;
import customization.ShowLanguage;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import main.Genres;
import main.Quality;
import platform.component.Show;
import static guis.NetflixFrame.shows;

/**
 *
 * @author oessf
 */
public class CRUDNetflixPanel extends javax.swing.JPanel {
    static DefaultListModel<Show> model;
    /**
     * Creates new form CRUDNetflixPanel
     */
    public CRUDNetflixPanel() {
        model = new DefaultListModel<>();
        initComponents();
        showList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        titleTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        namesTxt = new javax.swing.JTextField();
        viewsTxt = new javax.swing.JTextField();
        synopsisTxt = new javax.swing.JTextField();
        avgRatingTxt = new javax.swing.JTextField();
        totalWatchTxt = new javax.swing.JTextField();
        qualityCombo = new javax.swing.JComboBox<>();
        languageCombo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        actionCB = new javax.swing.JCheckBox();
        animeCB = new javax.swing.JCheckBox();
        familyCB = new javax.swing.JCheckBox();
        comediesCB = new javax.swing.JCheckBox();
        classicCB = new javax.swing.JCheckBox();
        dramasCB = new javax.swing.JCheckBox();
        horrorCB = new javax.swing.JCheckBox();
        romanticCB = new javax.swing.JCheckBox();
        scientificCB = new javax.swing.JCheckBox();
        sportsCB = new javax.swing.JCheckBox();
        tvshowsCB = new javax.swing.JCheckBox();
        maturityCombo = new javax.swing.JComboBox<>();
        dateTxt = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(34, 31, 31));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 241));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clapperboard.png"))); // NOI18N
        jLabel1.setText("Add a Show To Netflix");

        addBtn.setBackground(new java.awt.Color(229, 9, 20));
        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(245, 245, 241));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Create.png"))); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(229, 9, 20));
        editBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(245, 245, 241));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Modify.png"))); // NOI18N
        editBtn.setText("Edit");

        deleteBtn.setBackground(new java.awt.Color(229, 9, 20));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(245, 245, 241));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 9, 20));
        jLabel2.setText("Total Watch:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(229, 9, 20));
        jLabel3.setText("Title:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(229, 9, 20));
        jLabel4.setText("Release Date:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(229, 9, 20));
        jLabel5.setText("Quality:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(229, 9, 20));
        jLabel6.setText("Language:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(229, 9, 20));
        jLabel7.setText("Names:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(229, 9, 20));
        jLabel8.setText("Views:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(229, 9, 20));
        jLabel9.setText("Synopsis:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(229, 9, 20));
        jLabel10.setText("Avergae Rating:");

        jLabel11.setBackground(new java.awt.Color(229, 9, 20));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(229, 9, 20));
        jLabel11.setText("Maturity Levels:");

        qualityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Quality.values()));

        languageCombo.setModel(new javax.swing.DefaultComboBoxModel<>(ShowLanguage.values()));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(229, 9, 20));
        jLabel12.setText("Genres:");

        actionCB.setForeground(new java.awt.Color(184, 29, 36));
        actionCB.setText("Action");
        actionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionCBActionPerformed(evt);
            }
        });

        animeCB.setForeground(new java.awt.Color(184, 29, 36));
        animeCB.setText("Anime");
        animeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animeCBActionPerformed(evt);
            }
        });

        familyCB.setForeground(new java.awt.Color(184, 29, 36));
        familyCB.setText("Family");
        familyCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyCBActionPerformed(evt);
            }
        });

        comediesCB.setForeground(new java.awt.Color(184, 29, 36));
        comediesCB.setText("Comedies");
        comediesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comediesCBActionPerformed(evt);
            }
        });

        classicCB.setForeground(new java.awt.Color(184, 29, 36));
        classicCB.setText("Classic");

        dramasCB.setForeground(new java.awt.Color(184, 29, 36));
        dramasCB.setText("Dramas");

        horrorCB.setForeground(new java.awt.Color(184, 29, 36));
        horrorCB.setText("Horror");

        romanticCB.setForeground(new java.awt.Color(184, 29, 36));
        romanticCB.setText("Romantic");
        romanticCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romanticCBActionPerformed(evt);
            }
        });

        scientificCB.setForeground(new java.awt.Color(184, 29, 36));
        scientificCB.setText("Scientific");
        scientificCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scientificCBActionPerformed(evt);
            }
        });

        sportsCB.setForeground(new java.awt.Color(184, 29, 36));
        sportsCB.setText("Sports");
        sportsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsCBActionPerformed(evt);
            }
        });

        tvshowsCB.setForeground(new java.awt.Color(184, 29, 36));
        tvshowsCB.setText("TVShows");
        tvshowsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvshowsCBActionPerformed(evt);
            }
        });

        maturityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(MaturityLevel.values()));

        dateTxt.setColumns(8);
        dateTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        showList.setBackground(new java.awt.Color(184, 29, 36));
        showList.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        showList.setForeground(new java.awt.Color(245, 245, 241));
        showList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        showList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                showListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(showList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(44, 44, 44))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(75, 75, 75))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(52, 52, 52))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(85, 85, 85)))
                                .addGap(3, 3, 3)))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(romanticCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scientificCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sportsCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tvshowsCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(370, 370, 370))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actionCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(animeCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(familyCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comediesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classicCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dramasCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horrorCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(221, 221, 221))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(maturityCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalWatchTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(avgRatingTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(synopsisTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewsTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namesTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(languageCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(qualityCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(106, 106, 106)
                                .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(96, 96, 96)
                                .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(290, 290, 290))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qualityCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(languageCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namesTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewsTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(synopsisTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avgRatingTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalWatchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maturityCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actionCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animeCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(familyCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comediesCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classicCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dramasCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horrorCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(romanticCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scientificCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sportsCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvshowsCB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        
        String titleStr = titleTxt.getText();
        GregorianCalendar gre = new GregorianCalendar();
        gre.setTime((Date) dateTxt.getValue());
        Quality quality = (Quality) qualityCombo.getSelectedItem();
        ShowLanguage language = (ShowLanguage) languageCombo.getSelectedItem();
        String[] names = namesTxt.getText().split(",");
        String viewsStr = viewsTxt.getText();
        int views;
        try {
            views = Integer.parseInt(viewsStr);
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this, "Please, Enter an integer for the number of views!", "Add Show", JOptionPane.ERROR_MESSAGE);
        }
        String synopsis = synopsisTxt.getText();
        String avgRatingStr = avgRatingTxt.getText();
        double avgRating;
        try {
            avgRating = Double.parseDouble(avgRatingStr);
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this, "Please, Enter a double for the average rating!", "Add Show", JOptionPane.ERROR_MESSAGE);
        }
        String totalWatchStr = totalWatchTxt.getText();
        int totalWatch;
        try {
            totalWatch = Integer.parseInt(totalWatchStr);
        } catch (NumberFormatException err) {
            JOptionPane.showMessageDialog(CRUDNetflixPanel.this, "Please, Enter a integer for the total watch!", "Add Show", JOptionPane.ERROR_MESSAGE);
        }
        MaturityLevel level = (MaturityLevel) maturityCombo.getSelectedItem();
        ArrayList<MaturityLevel> levels = new ArrayList();
        if (level == MaturityLevel.KIDS) {
            levels.add(MaturityLevel.KIDS);
        } else if (level.equals(MaturityLevel.TEENS)) {
            levels.add(MaturityLevel.KIDS);
            levels.add(MaturityLevel.TEENS);
        } else if (level.equals(MaturityLevel.ADULT)) {
            levels.add(MaturityLevel.KIDS);
            levels.add(MaturityLevel.TEENS);
            levels.add(MaturityLevel.ADULT);
        } else if (level.equals(MaturityLevel.ADULTS)) {
            levels.add(MaturityLevel.KIDS);
            levels.add(MaturityLevel.TEENS);
            levels.add(MaturityLevel.ADULT);
            levels.add(MaturityLevel.ADULTS);
        } else {
            levels.add(MaturityLevel.KIDS);
            levels.add(MaturityLevel.TEENS);
            levels.add(MaturityLevel.ADULT);
            levels.add(MaturityLevel.ADULTS);
        }
        ArrayList<Genres> genres = new ArrayList();
        // Genres Checkboxes
        if (actionCB.isSelected()) {
            genres.add(Genres.ACTION);
        }
        if (animeCB.isSelected()) {
            genres.add(Genres.ANIME);
        }
        if (familyCB.isSelected()) {
            genres.add(Genres.FAMILY);
        }
        if (comediesCB.isSelected()) {
            genres.add(Genres.COMEDIES);
        }
        if (classicCB.isSelected()) {
            genres.add(Genres.CLASSIC);
        }
        if (dramasCB.isSelected()) {
            genres.add(Genres.DRAMAS);
        }
        if (horrorCB.isSelected()) {
            genres.add(Genres.HORROR);
        }
        if (romanticCB.isSelected()) {
            genres.add(Genres.ROMANTIC);
        }
        if (scientificCB.isSelected()) {
            genres.add(Genres.SCIENCEFICTION);
        }
        if (sportsCB.isSelected()) {
            genres.add(Genres.SPORTS);
        }
        if (tvshowsCB.isSelected()) {
            genres.add(Genres.TVSHOWS);
        }
        Show show = new Show(titleStr, gre, quality, genres, language, names, synopsis, levels);
        shows.addShow(show);
        System.out.println(shows.toString());
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void actionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionCBActionPerformed

    private void animeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animeCBActionPerformed

    private void familyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familyCBActionPerformed

    private void comediesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comediesCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comediesCBActionPerformed

    private void romanticCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romanticCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_romanticCBActionPerformed

    private void scientificCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scientificCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scientificCBActionPerformed

    private void sportsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportsCBActionPerformed

    private void tvshowsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvshowsCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvshowsCBActionPerformed

    private void showListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_showListValueChanged
        // TODO add your handling code here:
        if (evt.getValueIsAdjusting()) return;
        Show show = showList.getSelectedValue();
        if (show == null) return;
        
        titleTxt.setText(show.getTitle());
        dateTxt.setText(show.getRelease_date().toString());
        qualityCombo.setSelectedItem(show.getQuality());
        languageCombo.setSelectedItem(show.getLang());
        namesTxt.setText(String.join(", ",show.getNames()));
        viewsTxt.setText(String.valueOf(show.getNum_views()));
        synopsisTxt.setText(show.getSynopsis());
        avgRatingTxt.setText(String.valueOf(show.getAverage_rating()));
        totalWatchTxt.setText(String.valueOf(show.getTotal_watch()));
        maturityCombo.setSelectedItem(show.getLevels());
        // Genres Checkboxes
        for(Genres genre : show.getGenres()) {
            switch (genre.name()) {
                case "ACTION":
                    actionCB.setSelected(true);
                    break;
                case "ANIME":
                    animeCB.setSelected(true);
                    break;
                case "FAMILY":
                    familyCB.setSelected(true);
                    break;
                case "CLASSIC":
                    classicCB.setSelected(true);
                    break;
                case "COMEDIES":
                    comediesCB.setSelected(true);
                    break;
                case "DRAMAS":
                    dramasCB.setSelected(true);
                    break;
                case "HORROR":
                    horrorCB.setSelected(true);
                    break;
                case "ROMANTIC":
                    romanticCB.setSelected(true);
                    break;
                case "SCIENCEFICTION":
                    scientificCB.setSelected(true);
                    break;
                case "SPORTS":
                    sportsCB.setSelected(true);
                    break;
                case "TVSHOWS":
                    tvshowsCB.setSelected(true);
                    break;
            }
        }
    }//GEN-LAST:event_showListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox actionCB;
    private javax.swing.JButton addBtn;
    private javax.swing.JCheckBox animeCB;
    private javax.swing.JTextField avgRatingTxt;
    private javax.swing.JCheckBox classicCB;
    private javax.swing.JCheckBox comediesCB;
    private javax.swing.JFormattedTextField dateTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JCheckBox dramasCB;
    private javax.swing.JButton editBtn;
    private javax.swing.JCheckBox familyCB;
    private javax.swing.JCheckBox horrorCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<ShowLanguage> languageCombo;
    private javax.swing.JComboBox<MaturityLevel> maturityCombo;
    private javax.swing.JTextField namesTxt;
    private javax.swing.JComboBox<Quality> qualityCombo;
    private javax.swing.JCheckBox romanticCB;
    private javax.swing.JCheckBox scientificCB;
    private javax.swing.JList<Show> showList;
    private javax.swing.JCheckBox sportsCB;
    private javax.swing.JTextField synopsisTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextField totalWatchTxt;
    private javax.swing.JCheckBox tvshowsCB;
    private javax.swing.JTextField viewsTxt;
    // End of variables declaration//GEN-END:variables
}
