/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import javax.swing.table.DefaultTableModel;
import main.Genres;
import static guis.NetflixFrame.shows;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import platform.component.Show;
/**
 *
 * @author oessf
 */
public class ShowSearchPanel extends javax.swing.JPanel {
    DefaultTableModel model;
    String[] colNames = {"Title", "Release Date", "Quality", "Genres" ,"Language", "Names", 
            "Number of Views", "Synopsis", "Average Rating", "Levels", "Total Watch"};
    /**
     * Creates new form ShowSearchPanel
     */
    public ShowSearchPanel() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(colNames);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        searchBtn = new javax.swing.JButton();
        genreCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultTablr = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(34, 31, 31));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 241));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/searchBig.png"))); // NOI18N
        jLabel1.setText("Search For Shows");

        searchBtn.setBackground(new java.awt.Color(229, 9, 20));
        searchBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(245, 245, 241));
        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/View.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        genreCombo.setBackground(new java.awt.Color(229, 9, 20));
        genreCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genreCombo.setForeground(new java.awt.Color(245, 245, 241));
        genreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(Genres.values()));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 9, 20));
        jLabel2.setText("Search By Genre:");

        resultTablr.setModel(model
        );
        jScrollPane2.setViewportView(resultTablr);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 245, 241));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Hint.png"))); // NOI18N
        jLabel3.setText("Search Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(genreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(searchBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(genreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        Genres genre = (Genres) genreCombo.getSelectedItem();
        
        List<Show> results = shows.findShowWithGenre(genre);
        if (!results.isEmpty()) {
            Object [][] data = new Object[results.size()][colNames.length];
            for (int i =0; i < results.size(); i++) {
                Show show = results.get(i);
                data[i][0] = show.getTitle();
                data[i][1] = show.getRelease_date().getTime();
                data[i][2] = show.getQuality();
                data[i][3] = show.getGenres();
                data[i][4] = show.getLang();
                data[i][5] = Arrays.toString(show.getNames());
                data[i][6] = show.getNum_views();
                data[i][7] = show.getSynopsis();
                data[i][8] = show.getAverage_rating();
                data[i][9] = show.getLevels();
                data[i][10] = show.getTotal_watch();
            }
            model.setDataVector(data, colNames);
            
        } else {
            model.setDataVector(null, colNames);
            JOptionPane.showMessageDialog(ShowSearchPanel.this, "There is no result for this genre!", "Search Show", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        // Instead of else, implement an exception
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Genres> genreCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable resultTablr;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
